// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: hasher.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HasherService_Hash_FullMethodName = "/leadgen.hasher.v1.HasherService/Hash"
)

// HasherServiceClient is the client API for HasherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HasherServiceClient interface {
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
}

type hasherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHasherServiceClient(cc grpc.ClientConnInterface) HasherServiceClient {
	return &hasherServiceClient{cc}
}

func (c *hasherServiceClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, HasherService_Hash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HasherServiceServer is the server API for HasherService service.
// All implementations must embed UnimplementedHasherServiceServer
// for forward compatibility.
type HasherServiceServer interface {
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	mustEmbedUnimplementedHasherServiceServer()
}

// UnimplementedHasherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHasherServiceServer struct{}

func (UnimplementedHasherServiceServer) Hash(context.Context, *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (UnimplementedHasherServiceServer) mustEmbedUnimplementedHasherServiceServer() {}
func (UnimplementedHasherServiceServer) testEmbeddedByValue()                       {}

// UnsafeHasherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HasherServiceServer will
// result in compilation errors.
type UnsafeHasherServiceServer interface {
	mustEmbedUnimplementedHasherServiceServer()
}

func RegisterHasherServiceServer(s grpc.ServiceRegistrar, srv HasherServiceServer) {
	// If the following call pancis, it indicates UnimplementedHasherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HasherService_ServiceDesc, srv)
}

func _HasherService_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServiceServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HasherService_Hash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServiceServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HasherService_ServiceDesc is the grpc.ServiceDesc for HasherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HasherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leadgen.hasher.v1.HasherService",
	HandlerType: (*HasherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hash",
			Handler:    _HasherService_Hash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hasher.proto",
}
