// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: hasher.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashAlgorithm int32

const (
	HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED HashAlgorithm = 0
	HashAlgorithm_HASH_ALGORITHM_MD5         HashAlgorithm = 1
	HashAlgorithm_HASH_ALGORITHM_SHA256      HashAlgorithm = 2
)

// Enum value maps for HashAlgorithm.
var (
	HashAlgorithm_name = map[int32]string{
		0: "HASH_ALGORITHM_UNSPECIFIED",
		1: "HASH_ALGORITHM_MD5",
		2: "HASH_ALGORITHM_SHA256",
	}
	HashAlgorithm_value = map[string]int32{
		"HASH_ALGORITHM_UNSPECIFIED": 0,
		"HASH_ALGORITHM_MD5":         1,
		"HASH_ALGORITHM_SHA256":      2,
	}
)

func (x HashAlgorithm) Enum() *HashAlgorithm {
	p := new(HashAlgorithm)
	*p = x
	return p
}

func (x HashAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HashAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_hasher_proto_enumTypes[0].Descriptor()
}

func (HashAlgorithm) Type() protoreflect.EnumType {
	return &file_hasher_proto_enumTypes[0]
}

func (x HashAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HashAlgorithm.Descriptor instead.
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{0}
}

type HashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Algorithm     HashAlgorithm          `protobuf:"varint,2,opt,name=algorithm,proto3,enum=leadgen.hasher.v1.HashAlgorithm" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRequest) Reset() {
	*x = HashRequest{}
	mi := &file_hasher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRequest) ProtoMessage() {}

func (x *HashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hasher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRequest.ProtoReflect.Descriptor instead.
func (*HashRequest) Descriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{0}
}

func (x *HashRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *HashRequest) GetAlgorithm() HashAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return HashAlgorithm_HASH_ALGORITHM_UNSPECIFIED
}

type HashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashResponse) Reset() {
	*x = HashResponse{}
	mi := &file_hasher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashResponse) ProtoMessage() {}

func (x *HashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hasher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashResponse.ProtoReflect.Descriptor instead.
func (*HashResponse) Descriptor() ([]byte, []int) {
	return file_hasher_proto_rawDescGZIP(), []int{1}
}

func (x *HashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_hasher_proto protoreflect.FileDescriptor

const file_hasher_proto_rawDesc = "" +
	"\n" +
	"\fhasher.proto\x12\x11leadgen.hasher.v1\"c\n" +
	"\vHashRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\x12>\n" +
	"\talgorithm\x18\x02 \x01(\x0e2 .leadgen.hasher.v1.HashAlgorithmR\talgorithm\"\"\n" +
	"\fHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash*b\n" +
	"\rHashAlgorithm\x12\x1e\n" +
	"\x1aHASH_ALGORITHM_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12HASH_ALGORITHM_MD5\x10\x01\x12\x19\n" +
	"\x15HASH_ALGORITHM_SHA256\x10\x022X\n" +
	"\rHasherService\x12G\n" +
	"\x04Hash\x12\x1e.leadgen.hasher.v1.HashRequest\x1a\x1f.leadgen.hasher.v1.HashResponseB6Z4github.com/tmybsv/leadgen-test-task/pkg/pb/hasher/v1b\x06proto3"

var (
	file_hasher_proto_rawDescOnce sync.Once
	file_hasher_proto_rawDescData []byte
)

func file_hasher_proto_rawDescGZIP() []byte {
	file_hasher_proto_rawDescOnce.Do(func() {
		file_hasher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hasher_proto_rawDesc), len(file_hasher_proto_rawDesc)))
	})
	return file_hasher_proto_rawDescData
}

var file_hasher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hasher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hasher_proto_goTypes = []any{
	(HashAlgorithm)(0),   // 0: leadgen.hasher.v1.HashAlgorithm
	(*HashRequest)(nil),  // 1: leadgen.hasher.v1.HashRequest
	(*HashResponse)(nil), // 2: leadgen.hasher.v1.HashResponse
}
var file_hasher_proto_depIdxs = []int32{
	0, // 0: leadgen.hasher.v1.HashRequest.algorithm:type_name -> leadgen.hasher.v1.HashAlgorithm
	1, // 1: leadgen.hasher.v1.HasherService.Hash:input_type -> leadgen.hasher.v1.HashRequest
	2, // 2: leadgen.hasher.v1.HasherService.Hash:output_type -> leadgen.hasher.v1.HashResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hasher_proto_init() }
func file_hasher_proto_init() {
	if File_hasher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hasher_proto_rawDesc), len(file_hasher_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hasher_proto_goTypes,
		DependencyIndexes: file_hasher_proto_depIdxs,
		EnumInfos:         file_hasher_proto_enumTypes,
		MessageInfos:      file_hasher_proto_msgTypes,
	}.Build()
	File_hasher_proto = out.File
	file_hasher_proto_goTypes = nil
	file_hasher_proto_depIdxs = nil
}
